targets:
  $default:
    builders:
      sql_meta_data|table_builder:
        enabled: true
      sql_meta_data|scanner_builder:
        enabled: true
      sql_meta_data|column_builder:
        enabled: false
      sql_meta_data|id_builder:
        enabled: false

builders:
  table_builder:
    import: 'package:sql_meta_data/builder.dart'
    builder_factories: ['tableBuilder']
    build_extensions: {'.dart':['.table.dart']}
    auto_apply: dependents
    build_to: source
    runs_before: ['sql_meta_data|scanner_builder']
  scanner_builder:
    import: 'package:sql_meta_data/builder.dart'
    builder_factories: ['scannerBuilder']
    build_extensions: {'.dart':['.scanner.dart']}
    auto_apply: dependents
    build_to: source
  column_builder:
    import: 'package:sql_meta_data/builder.dart'
    builder_factories: ['columnBuilder']
    build_extensions: {'.dart':['.column.dart']}
    build_to: source
    runs_before: ['sql_meta_data|table_builder']
  id_builder:
    import: 'package:sql_meta_data/builder.dart'
    builder_factories: ['IDBuilder']
    build_extensions: {'.dart':['.primary.dart']}
    build_to: source
    runs_before: ['sql_meta_data|table_builder']